# -*- coding: utf-8 -*-
"""pytoch_excercise_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFQ6y0mgrcJ7qJPWk8i0Qj4WNkNm7py3
"""

import torch

x=torch.empty(1)

x

y=torch.empty(2,2,3)

y

z=torch.rand(2,2)
z

z=torch.ones(2,2,2,2)
z

z=torch.ones(2,2,2,2,dtype=torch.int)
z

z.type()

x=torch.rand(2,2)
y=torch.rand(2,2)
z=x+y
z
z=torch.add(x,y)
z

z=x-y
z

z=torch.sub(x,y)
z

z=torch.mul(x,y)
z

z=torch.div(x,y)
z

x=torch.rand(5,3)
x

print(x[:,0])

print(x[1,1].item())

x=torch.rand(4,4)
x

# y=x.view(16)
y

y=x.view(-1,8)
print(y)
print(y.size())

import numpy as np

a=torch.ones(5)
a

b=a.numpy()
print(type(b))

print(b)

a.add_(1)
a

b

a=torch.ones(5)

b=torch. from_numpy(a)
print(b)

a +=1
print(a)

if torch.cuda.is_available():
  device=torch.device('cuda')
  x=torch.ones(5,device=device)
  y=torch.ones(5)
  y=y.to(device)
  z=x+y
  z=z.to('cpu')

x=torch.ones(5,requires_grad=True)
x



















